# Generated by Django 4.1.13 on 2024-05-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_vr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='vr_image',
            field=models.ImageField(null=True, upload_to='vr_images/'),
        ),
    ]
