# Generated by Django 4.1.13 on 2024-05-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_vr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='vr_image',
        ),
    ]
