# Generated by Django 4.1.13 on 2024-05-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0004_remove_location_vr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('HIGH', 'Hard'), ('MEDIUM', 'Medium'), ('EASY', 'Easy')], default='MEDIUM', max_length=250)),
                ('distance', models.CharField(max_length=250)),
                ('audience', models.CharField(max_length=250)),
                ('locations', models.ManyToManyField(through='route.Path', to='location.location')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
    ]
