# Generated by Django 4.1.13 on 2024-05-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0004_remove_location_vr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(null=True, upload_to='vr_images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vrphoto', to='location.location')),
            ],
        ),
    ]
